# Часть 1

In [2]:
import numpy as np

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

Ответ:

а- не может быть произведения

б- А*В = 2х5 * 5х3 = 2х3 - размерность 

в- 2 варианта А*В / В*А = 8Х8 / 3х3

г - также 2 варианта 4х4

2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [8]:
A = np.array([[1,-2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(A)
print(B)
print(A + B)


[[ 1 -2]
 [ 3  0]]
[[ 4 -1]
 [ 0  5]]
[[ 5 -3]
 [ 3  5]]


In [9]:
print(np.dot(A, B))

[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [10]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
combo = 3*A - 2*B + 4*C
print(combo)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [11]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
print(A_T)

[[ 4  5  2]
 [ 1 -2  3]]


In [12]:
var_a = A.dot(A_T)
var_b = A_T.dot(A)
print(var_a)
print(var_b)

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [23]:
def matrix_multiply(A, B):
    m_1 = len(A)
    n_1 = len(A[0])
    m_2 = len(B)
    n_2 = len(B[0])

    s = 0  # сумма
    t = []  # временная матрица
    C = []  # конечная матрица

    if n_1 != m_2:
        print('Impossible')
    else:
        for z in range(0, m_1):
            for j in range(0, n_2):
                for i in range(0, n_1):
                    s += A[z][i] * B[i][j]
                t.append(s)
                s = 0
            C.append(t)
            t = []
    return C

A = [[4, 1], [5, -2], [2, 3]]
B = [[4,  5, 2], [1, -2,  3]]
print("AxB\n",matrix_multiply(A, B))

AxB
 [[17, 18, 11], [18, 29, 4], [11, 4, 13]]


# Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Задание 1:

А)sin(x)*sin(x) + cos(x)*cos(x) = sin(x)^2 + cos(x)^2 = 1

Определитель равен "1"

Б): Так как матрица треугольня то достаточно посчитать произвдение элементов по главной диагонали

In [2]:
import numpy as np
import scipy.linalg

In [1]:
det_b = 4 * 5 * 9
print(det_b)

180


In [4]:
matrix = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(matrix)
print(f'Определитель: {np.linalg.det(matrix):.0f}')

[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель: 180


В):

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(f'Определитель: {np.linalg.det(matrix):.0f}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель: 0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а)так как det(A^2) = det(A) * det(A), то 4 * 4 = 16

б) Определитель транспонированной матрицы равен определителю исходной матрицы - то есть 4

в)По аналогии с первым вариантом определитель будет равен 8 

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю.

In [6]:
matrix = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(matrix)
print(f'Определитель: {np.linalg.det(matrix):.0f}')

[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель: 0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [7]:
matrix = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(matrix)
print(f'Ранг матрицы: {np.linalg.matrix_rank(matrix):.0f}')

[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [8]:
matrix = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 2], [2, 3, 5, 6]])
print(matrix)
print(f'Ранг матрицы: {np.linalg.matrix_rank(matrix):.0f}')

[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 2]
 [2 3 5 6]]
Ранг матрицы: 3
