__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [1]:
import numpy as np

In [3]:
a = np.array([[-1, -6], [2, 6]])
v, w = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
Собственные векторы:
[2. 3.]


Задача 2:

In [4]:
a = np.array([[-1, 0], [0, -1]])
v, w = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[[1. 0.]
 [0. 1.]]
Собственные векторы:
[-1. -1.]


Получается оператор у нас еденичный, значит и матрицы у нас будет всегда в еденичном базисе и отталкиваясь от этого любой вектор будет собстсвенным для оператора

Задача 3:

In [5]:
a = np.array([[1, 1], [-1, 3]])
v, w = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]
Собственные векторы:
[2.00000002 1.99999998]


При векторе (1, 1) значения сигмы получаются 0 и -4, значит такая система не имеет значения

Задача 4:

In [6]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
v, w = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Собственные векторы:
[ 3. -3.  3.]


По подсчетам вектор (3, -3, -4) также является собсвтенным при сигма = -3